wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: Epoch
    - 1: Validation PPL
      5: 1
      6:
      - 1
      - 3
    - 1: Test PPL
      5: 1
      6:
      - 1
      - 3
    python_version: 3.6.10
    start_time: 1664392856.068447
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 7
      - 13
      - 15
      - 23
      4: 3.6.10
      5: 0.13.3
      8:
      - 5
